// Miejsca do pracy w Warszawie.
// Współrzędne i godziny: OpenStreetMap (Nominatim), stan na październik 2026.
// Oceny "do pracy" są redakcyjne: zebrane z przewodników i z arkusza Miejsca_do_pracy_Warszawa.xlsx.
//
// Pola:
//   type     kawiarnia | coworking | biblioteka | darmowe
//   score    1–5, jak dobrze się tu pracuje
//   wifi     1–5 albo null (brak danych)
//   outlets  "dużo" | "średnio" | "mało" | null
//   noise    "cicho" | "umiarkowanie" | "gwarno" | null
//   laptop   "tak" | "ograniczenia"
//   hours    format OSM opening_hours (Mo-Fr 08:00-20:00; Sa 09:00-18:00) albo null
//   verify   true = dane starsze lub niepełne, sprawdź przed wizytą

window.PLACES = [
  // ───────────── Kawiarnie ─────────────
  {
    id: "coffeedesk-wilcza",
    name: "Coffeedesk Wilcza",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Wilcza 42",
    lat: 52.22456, lng: 21.01361,
    score: 5, wifi: 5, outlets: "dużo", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 07:30-20:00; Sa 09:00-20:00; Su 10:00-20:00",
    cost: "cena konsumpcji",
    why: "Trochę kawiarnia, trochę hot desk. Wspólne i pojedyncze stoły, gniazdka przy większości miejsc, mocne Wi-Fi i kawa speciality od największego sklepu kawowego w Polsce.",
    tip: "Sala jest niewielka i szybko się zapełnia. Najlepiej przyjść przed 10:00.",
  },
  {
    id: "coffeedesk-prozna",
    name: "Coffeedesk Próżna",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Próżna 7",
    lat: 52.23629, lng: 21.00473,
    score: 5, wifi: 5, outlets: "dużo", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 08:00-20:00; Sa-Su 09:00-20:00",
    cost: "cena konsumpcji",
    why: "Dużo światła dziennego, stoły wspólne i lounge, latem ogródek. O każdej porze siedzi tu ktoś z laptopem, a ludzie spokojnie prowadzą calle.",
    tip: "Dwie minuty od metra Świętokrzyska.",
  },
  {
    id: "coffeedesk-powisle",
    name: "Coffeedesk Powiśle",
    type: "kawiarnia",
    district: "Powiśle",
    address: "Elektryczna 2A",
    lat: 52.23983, lng: 21.02990,
    score: 4, wifi: 5, outlets: "średnio", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 07:30-21:00; Sa-Su 09:00-20:00",
    cost: "cena konsumpcji",
    why: "Ta sama sieć i ten sam laptopowy klimat, a do tego otwarte do 21:00 w tygodniu. Dobry wybór na Powiślu, kiedy STOR i Labour są pełne.",
  },
  {
    id: "coffeedesk-panska",
    name: "Coffeedesk Pańska",
    type: "kawiarnia",
    district: "Wola",
    address: "Pańska 97",
    lat: 52.23051, lng: 20.98933,
    score: 4, wifi: 5, outlets: "średnio", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 07:30-20:00; Sa-Su 10:00-18:00",
    cost: "cena konsumpcji",
    why: "Coffeedesk w biurowej części Woli. W tygodniu spokojnie pracuje się tu od rana, a w zasięgu spaceru masz Rondo Daszyńskiego.",
  },
  {
    id: "labour",
    name: "Labour Cafe & Co-working",
    type: "kawiarnia",
    district: "Powiśle",
    address: "Tamka 49",
    lat: 52.23615, lng: 21.02085,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Kawiarnia pomyślana od początku dla freelancerów: duże stoły, wygodne krzesła, cisza i gniazdka przy stanowiskach. Drukarka, ksero, skaner i flipcharty są dostępne za darmo.",
    tip: "Bywają tu eventy i networking dla pracujących zdalnie.",
  },
  {
    id: "wrzenie-swiata",
    name: "Wrzenie Świata",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Gałczyńskiego 7",
    lat: 52.23489, lng: 21.01947,
    score: 5, wifi: 5, outlets: null, noise: "cicho", laptop: "tak",
    hours: "Mo-Su 10:00-22:00",
    cost: "cena konsumpcji",
    why: "Kawiarnia i księgarnia z reportażami, a w niej osobny Quiet Room do pracy z laptopem. Wi-Fi bez limitu, latem taras pod drzewami, dwa kroki od Nowego Światu.",
    tip: "W weekendy do 13:00 jest bufet śniadaniowy.",
  },
  {
    id: "stor-bracka",
    name: "STOR Bracka",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Bracka 18",
    lat: 52.23183, lng: 21.01688,
    score: 4, wifi: 4, outlets: "średnio", noise: "umiarkowanie", laptop: "ograniczenia",
    hours: "Mo-Fr 08:30-21:00; Sa-Su 09:30-21:00",
    cost: "cena konsumpcji",
    why: "Kameralna kawiarnia speciality przy metrze Centrum, z antresolą i gniazdkami w zasięgu ręki. Dobra na szybką robotę administracyjną między spotkaniami.",
    warn: "Część stolików to strefa bez laptopów, w weekendy jest jej więcej.",
  },
  {
    id: "stor-tamka",
    name: "STOR Tamka",
    type: "kawiarnia",
    district: "Powiśle",
    address: "Tamka 33",
    lat: 52.23684, lng: 21.02471,
    score: 3, wifi: 4, outlets: "mało", noise: "umiarkowanie", laptop: "ograniczenia",
    hours: "Mo-Fr 08:30-21:00; Sa-Su 09:30-21:00",
    cost: "cena konsumpcji",
    why: "Pierwszy STOR i jedna z najlepszych kaw w mieście. Piękne, pełne roślin wnętrze, ale lokal jest mały i często pełny.",
    warn: "Strefy bez laptopów, w weekendy większe. Po miejsce przy gniazdku trzeba przyjść rano.",
  },
  {
    id: "ministerstwo-kawy",
    name: "Ministerstwo Kawy",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Marszałkowska 27/35",
    lat: 52.21877, lng: 21.01830,
    score: 4, wifi: 4, outlets: "średnio", noise: "umiarkowanie", laptop: "ograniczenia",
    hours: "Mo-Fr 08:00-20:30; Sa-Su 08:30-20:30",
    cost: "cena konsumpcji",
    why: "Klasyk warszawskiego speciality przy placu Unii Lubelskiej. Stabilne Wi-Fi, stoły w sam raz pod laptopa i świeże wypieki.",
    warn: "W weekendy laptopy są zakazane. W tygodniu są wydzielone strefy do pracy, a w szczycie robi się tłoczno.",
  },
  {
    id: "filtry",
    name: "Filtry Cafe",
    type: "kawiarnia",
    district: "Ochota",
    address: "Niemcewicza 3",
    lat: 52.22046, lng: 20.98872,
    score: 4, wifi: 4, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 08:00-20:00; Sa 09:00-20:00; Su 10:00-20:00",
    cost: "cena konsumpcji",
    why: "Najstarsza kawiarnia speciality w Warszawie, działa od 2007 roku. Na starej Ochocie, z dala od zgiełku centrum. Słynie z drożdżówek cynamonowych.",
  },
  {
    id: "starbucks-norway-house",
    name: "Starbucks Norway House",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Lwowska 19",
    lat: 52.22267, lng: 21.01250,
    score: 4, wifi: 5, outlets: "dużo", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Su 07:00-21:30",
    cost: "cena konsumpcji",
    why: "Jeden z największych Starbucksów w mieście: 68 miejsc, stoły konferencyjne, dużo gniazdek i szybkie Wi-Fi. Przewidywalny wybór na cały dzień.",
  },
  {
    id: "nero-nowy-swiat",
    name: "Green Caffè Nero Nowy Świat",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Nowy Świat 53",
    lat: 52.23568, lng: 21.01810,
    score: 4, wifi: 4, outlets: "dużo", noise: "gwarno", laptop: "tak",
    hours: "Mo-Su 07:00-23:00",
    cost: "cena konsumpcji",
    why: "Sieć otwarta na laptopy: duże sale, wspólne stoły i mnóstwo gniazdek. Ten lokal jest otwarty do 23:00, więc nadaje się na wieczorne domykanie zadań.",
    tip: "Nero ma lokale w prawie każdej dzielnicy, warunki są wszędzie podobne.",
  },
  {
    id: "nero-koszykowa",
    name: "Green Caffè Nero Koszykowa",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Koszykowa 54",
    lat: 52.22293, lng: 21.01290,
    score: 4, wifi: 4, outlets: "dużo", noise: "gwarno", laptop: "tak",
    hours: "Mo-Sa 07:00-20:00; Su 08:00-19:00",
    cost: "cena konsumpcji",
    why: "Duża sala tuż obok Hali Koszyki. Łatwo znaleźć wolne miejsce z gniazdkiem, choć w porze lunchu jest głośniej.",
  },
  {
    id: "na-bank",
    name: "Na Bank Specialty Coffee",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Nowogrodzka 46",
    lat: 52.22823, lng: 21.00894,
    score: 4, wifi: 5, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Jasne, przestronne wnętrze i bardzo dobre Wi-Fi, a do tego śniadania i lunche na miejscu. Blisko Dworca Centralnego.",
    warn: "W porze brunchu robi się tłoczno.",
    verify: true,
  },
  {
    id: "relaks",
    name: "Cafe Relaks",
    type: "kawiarnia",
    district: "Mokotów",
    address: "Puławska 48",
    lat: 52.20268, lng: 21.02167,
    score: 4, wifi: 4, outlets: "średnio", noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 08:00-20:00; Sa-Su 09:00-20:00",
    cost: "cena konsumpcji",
    why: "Jasna, przestronna kawiarnia na Mokotowie, bardzo popularna wśród pracujących zdalnie. Dużo stolików i spokojne poranki w tygodniu.",
    warn: "W weekendy bywa głośno.",
  },
  {
    id: "kubek-w-kubek",
    name: "Kubek w Kubek",
    type: "kawiarnia",
    district: "Mokotów",
    address: "Grażyny 16",
    lat: 52.20386, lng: 21.02057,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: "Mo-Sa 08:00-19:00; Su 09:00-18:00",
    cost: "cena konsumpcji",
    why: "Spokojna, sąsiedzka kawiarnia na starym Mokotowie. Cicho, są gniazdka i nikt nie liczy, ile godzin siedzisz.",
  },
  {
    id: "u-krawca",
    name: "U Krawca Cafe",
    type: "kawiarnia",
    district: "Praga-Południe",
    address: "Siennicka 3",
    lat: 52.24434, lng: 21.07772,
    score: 4, wifi: 5, outlets: null, noise: "cicho", laptop: "tak",
    hours: "Mo-Fr 07:30-20:00; Sa-Su 09:00-20:00",
    cost: "cena konsumpcji",
    why: "Na Grochowie: dobra kawa, domowe wypieki i świeże kwiaty na stolikach. Cicho, wygodnie i z szybkim Wi-Fi.",
  },
  {
    id: "kafka",
    name: "Caffe Kafka",
    type: "kawiarnia",
    district: "Powiśle",
    address: "Oboźna 3",
    lat: 52.23953, lng: 21.02271,
    score: 4, wifi: null, outlets: null, noise: "cicho", laptop: "tak",
    hours: "Mo-Fr 09:00-22:00; Sa-Su 09:30-22:00",
    cost: "cena konsumpcji",
    why: "Wnętrze jak ze starego antykwariatu, z cichymi kątami do pisania. Blisko kampusu UW i otwarte do 22:00.",
  },
  {
    id: "jaskolka",
    name: "Bistro Jaskółka",
    type: "kawiarnia",
    district: "Żoliborz",
    address: "pl. Wilsona 4",
    lat: 52.26966, lng: 20.98523,
    score: 4, wifi: null, outlets: null, noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Dwie sale, a w tylnej zwykle jest cicho. Dobra kawa (także na owsianym), wegańskie menu i ceramika na półkach. Wychodzisz prosto na metro Plac Wilsona.",
    verify: true,
  },
  {
    id: "fawory",
    name: "Fawory",
    type: "kawiarnia",
    district: "Żoliborz",
    address: "Mickiewicza 21",
    lat: 52.26254, lng: 20.99163,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Żoliborska kawiarnia na spokojną pracę: cicho, są gniazdka, a obok park i Dom Kultury Słonecznik.",
    verify: true,
  },
  {
    id: "fabryczna",
    name: "Kawiarnia Fabryczna",
    type: "kawiarnia",
    district: "Powiśle",
    address: "Fabryczna 28/30",
    lat: 52.22428, lng: 21.03571,
    score: 4, wifi: null, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-Fr 07:30-18:00; Sa-Su 08:30-17:00",
    cost: "cena konsumpcji",
    why: "Fotele i domowy klimat w cichej części Powiśla, niedaleko Wisły. Dobra na długie, nieśpieszne sesje.",
    verify: true,
  },
  {
    id: "waszyngton",
    name: "Kawiarnia Waszyngton",
    type: "kawiarnia",
    district: "Praga-Południe",
    address: "al. Waszyngtona 96A",
    lat: 52.24237, lng: 21.07376,
    score: 4, wifi: null, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: "Mo-We 09:00-20:00; Th-Sa 09:00-22:00; Su 09:00-20:00",
    cost: "cena konsumpcji",
    why: "Przeszklony pawilon, w którym jest jasno i przestronnie. Na przerwę masz pod ręką spacer.",
    verify: true,
  },
  {
    id: "charlotte",
    name: "Charlotte",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "pl. Zbawiciela 4",
    lat: 52.22009, lng: 21.01864,
    score: 3, wifi: 3, outlets: "średnio", noise: "gwarno", laptop: "tak",
    hours: "Mo-Th 07:00-24:00; Fr 07:00-01:00; Sa 08:00-01:00; Su 08:00-22:00",
    cost: "cena konsumpcji",
    why: "Najlepsza na poranną pracę przy croissancie, zanim zejdzie się tłum. Duże wspólne stoły i otwarte od 7:00.",
    warn: "Od południa gwarno, trudno o calle.",
  },
  {
    id: "vincent",
    name: "Vincent Nowy Świat",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Nowy Świat 64",
    lat: 52.23620, lng: 21.01841,
    score: 3, wifi: null, outlets: null, noise: "gwarno", laptop: "tak",
    hours: "Mo-Th 07:30-22:00; Fr-Sa 07:30-24:00; Su 07:30-22:00",
    cost: "cena konsumpcji",
    why: "Francuska piekarnia otwarta od 7:30 do późna. Przytulna na godzinę maili, ale raczej nie na cały dzień.",
  },
  {
    id: "przegryz",
    name: "Przegryź",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Mokotowska 52",
    lat: 52.22568, lng: 21.02208,
    score: 3, wifi: null, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Dobra na poranną pracę przy śniadaniu w okolicach placu Trzech Krzyży.",
    verify: true,
  },
  {
    id: "hala-koszyki",
    name: "Hala Koszyki",
    type: "kawiarnia",
    kind: "Food hall",
    district: "Śródmieście",
    address: "Koszykowa 63",
    lat: 52.22222, lng: 21.01102,
    score: 3, wifi: 3, outlets: "średnio", noise: "gwarno", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Dużo miejsc, Wi-Fi i jedzenie z kilkunastu kuchni pod jednym dachem. Dobra na pracę przed południem, zanim zacznie się lunch.",
    warn: "Od 12:00 głośno i tłoczno.",
  },
  {
    id: "deski",
    name: "DeSki w Porcie Czerniakowskim",
    type: "kawiarnia",
    district: "Śródmieście",
    address: "Port Czerniakowski",
    lat: 52.22236, lng: 21.04770,
    score: 3, wifi: null, outlets: null, noise: "umiarkowanie", laptop: "tak",
    hours: null,
    cost: "cena konsumpcji",
    why: "Duży taras nad Wisłą i lunche. Praca z widokiem na wodę, ale głównie w ciepłym sezonie.",
    warn: "Działa sezonowo.",
    verify: true,
  },

  // ───────────── Coworkingi ─────────────
  {
    id: "wework-grzybowska",
    name: "WeWork Grzybowska",
    type: "coworking",
    district: "Wola",
    address: "Grzybowska 60/62",
    lat: 52.23437, lng: 20.98606,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "od 115 zł/dzień · All Access od 999 zł/mies.",
    why: "Hot desk na dzień przez WeWork On Demand, budki telefoniczne i sale na godziny. Dwa budynki obok siebie.",
    url: "https://www.wework.com",
  },
  {
    id: "wework-prosta",
    name: "WeWork Prosta 20",
    type: "coworking",
    district: "Wola",
    address: "Prosta 20 (Mennica Legacy Tower)",
    lat: 52.23285, lng: 20.99236,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "od 115 zł/dzień · All Access od 999 zł/mies.",
    why: "Hot desk na dzień w Mennica Legacy Tower, kilka minut od metra Rondo Daszyńskiego. Budki telefoniczne i sale na godziny.",
    url: "https://www.wework.com",
  },
  {
    id: "regus-polna",
    name: "Regus Polna Corner",
    type: "coworking",
    district: "Śródmieście",
    address: "Polna 11",
    lat: 52.21809, lng: 21.01436,
    score: 4, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "ok. 95 zł/dzień · biurko 549–1249 zł/mies.",
    why: "Karnety na 5 albo 10 dni w miesiącu lub bez limitu dni. Metro Politechnika masz tuż obok.",
    url: "https://www.regus.com",
  },
  {
    id: "spaces-koneser",
    name: "Spaces Koneser",
    type: "coworking",
    district: "Praga-Północ",
    address: "pl. Konesera 12",
    lat: 52.25567, lng: 21.04647,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "ok. 95 zł/dzień (sieć IWG)",
    why: "Trzy piętra w Centrum Praskim Koneser, dla członków dostęp 24/7. Kiedy potrzebujesz przerwy, na dole masz knajpy i kawiarnie.",
    url: "https://www.spacesworks.com",
  },
  {
    id: "brain-embassy-czackiego",
    name: "Brain Embassy Czackiego",
    type: "coworking",
    district: "Śródmieście",
    address: "Czackiego 15/17",
    lat: 52.23750, lng: 21.01451,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena na zapytanie",
    why: "Coworking w dawnym Teatrze Kwadrat, otwarty 24/7. Mocna społeczność i regularne eventy.",
    url: "https://brainembassy.com",
  },
  {
    id: "brain-embassy-jerozolimskie",
    name: "Brain Embassy Jerozolimskie",
    type: "coworking",
    district: "Ochota",
    address: "Al. Jerozolimskie 181B",
    lat: 52.21035, lng: 20.95274,
    score: 4, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena na zapytanie",
    why: "Brain Embassy w Adgar Park West. Spokojnie i z dala od centrum, dobra opcja dla mieszkających na Ochocie i we Włochach.",
    url: "https://brainembassy.com",
  },
  {
    id: "brain-embassy-postepu",
    name: "Brain Embassy Postępu",
    type: "coworking",
    district: "Mokotów",
    address: "Postępu 15",
    lat: 52.18053, lng: 20.99628,
    score: 4, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena na zapytanie",
    why: "Coworking w biurowym zagłębiu Mokotowa (Adgar Plaza). Sieć słynie z mocnej społeczności i eventów.",
    url: "https://brainembassy.com",
  },
  {
    id: "mindspace-koszyki",
    name: "Mindspace Koszyki",
    type: "coworking",
    district: "Śródmieście",
    address: "Koszykowa 61",
    lat: 52.22229, lng: 21.01178,
    score: 5, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "cena na zapytanie",
    why: "Designerskie wnętrza w kompleksie Koszyki, a Hala z jedzeniem jest piętro niżej.",
    url: "https://www.mindspace.me",
  },
  {
    id: "business-lab",
    name: "Business Lab Nowy Świat",
    type: "coworking",
    district: "Śródmieście",
    address: "Nowy Świat 41A",
    lat: 52.23436, lng: 21.01859,
    score: 4, wifi: 5, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "od €16/dzień (ok. 70 zł)",
    why: "Jedno z najtańszych wejść dziennych w ścisłym centrum. Można tu też wykupić wirtualne biuro.",
  },

  // ───────────── Biblioteki ─────────────
  {
    id: "buw",
    name: "BUW – Biblioteka Uniwersytecka",
    type: "biblioteka",
    district: "Powiśle",
    address: "Dobra 56/66",
    lat: 52.24264, lng: 21.02507,
    score: 5, wifi: 4, outlets: "dużo", noise: "cicho", laptop: "tak",
    hours: "Mo-Sa 09:00-21:00; Su 15:00-20:00",
    cost: "bezpłatnie",
    why: "Blisko 1000 miejsc do pracy i słynny ogród na dachu na przerwy. Najlepsze miejsce w mieście, kiedy potrzebujesz absolutnej ciszy.",
    warn: "Część przestrzeni wymaga karty bibliotecznej.",
    url: "https://www.buw.uw.edu.pl",
  },
  {
    id: "koszykowa",
    name: "Biblioteka na Koszykowej",
    type: "biblioteka",
    district: "Śródmieście",
    address: "Koszykowa 26/28",
    lat: 52.22237, lng: 21.01862,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: "Mo 13:00-20:45; Tu-Fr 09:00-20:45; Sa 10:00-16:45",
    cost: "bezpłatnie",
    why: "Główna biblioteka publiczna miasta w zabytkowym gmachu. Obowiązuje cisza, Wi-Fi jest za darmo.",
    url: "https://www.koszykowa.pl",
  },

  // ───────────── Za darmo / miejskie ─────────────
  {
    id: "erste-targowa",
    name: "Erste NetWork Spot Targowa",
    type: "darmowe",
    district: "Praga-Północ",
    address: "Targowa 49/51",
    lat: 52.25146, lng: 21.03793,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: "Mo-Fr 10:00-17:00",
    cost: "bezpłatnie",
    why: "Bezpłatny coworking w oddziale banku: 8 miejsc, Wi-Fi, kawa, drukarka i silent box.",
    tip: "Salki można rezerwować do 2 h dziennie (maks. 4 h tygodniowo).",
  },
  {
    id: "erste-krakowska",
    name: "Erste NetWork Spot Krakowska",
    type: "darmowe",
    district: "Włochy",
    address: "al. Krakowska 110/114",
    lat: 52.17681, lng: 20.94556,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: "Mo-Fr 10:00-17:00",
    cost: "bezpłatnie",
    why: "Te same zasady co na Targowej. Z open space korzystasz bez rezerwacji, w godzinach pracy oddziału.",
  },
  {
    id: "smolna",
    name: "Centrum Przedsiębiorczości Smolna",
    type: "darmowe",
    district: "Śródmieście",
    address: "Smolna 4",
    lat: 52.23404, lng: 21.02735,
    score: 4, wifi: 4, outlets: "średnio", noise: "cicho", laptop: "tak",
    hours: null,
    cost: "biurka po stawkach preferencyjnych · doradztwo bezpłatne",
    why: "Miejski coworking, a przy nim bezpłatne doradztwo prawne i księgowe oraz szkolenia dla przedsiębiorców.",
  },
];
